### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by brettfo** [IxMilia/Stl#8]
I'd like to migrate this repo to be under the MIT license, but first I need signoff from all past contributors.

@xfischer if you agree to the license migration, could you add a comment below indicating this?  Relevant commit:
- fixed commas as decimal separator using invariant culture (71d79245e1f6fd5cee688d2d432cc4a2f55a1827)

**Comment by xfischer** [comment]
Hi ! Yes OK for me. I’ll update my licenses. Why did you choose to change ?

**Comment by brettfo** [comment]
Thanks for the willingness!

I've been contacted by an app developer who wanted to use other projects in the IxMilia organization in closed-source software, and MIT is a little more permissive in this regard, so I'm going through all other projects and migrating to MIT where possible.

**Comment by xfischer** [comment]
Thanks for the insights :)
